name: build configurations

on:
  pull_request:
    branches:
      - main

jobs:
  build-configuration:
    permissions: write-all 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Install Poetry
        run: |
          mkdir dist
          gcc src/configuration.c -o dist/configuration
          
      - name: Read release.md file
        run: |
          RELEASE_BODY=$(cat release.md)
          echo "::set-output name=release_body::$RELEASE_BODY"

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: dist/console-${{ steps.extract_version.outputs.version }}.tar.gz
      #     asset_name: console-${{ steps.extract_version.outputs.version }}.tar.gz
      #     tag: v${{ steps.extract_version.outputs.version }}
      #     overwrite: true
      #     body: |
      #       ${{ steps.read_release.outputs.release_body }}